### ISSUE TITLE
StatisticsUtils crashing with various inputs

### ISSUE THREAD

**Issue by bvdheiden** [bvdheiden/TI1A2P1#3]
I've found that in the StatisticsUtils class the following methods crashed with given inputs:

- [average method](https://github.com/bvdheiden/TI1A2P1/blob/week-6/src/StatisticsUtils.java#L11) crashes with an empty list or with all values set to 0.
- [standardDeviation method](https://github.com/bvdheiden/TI1A2P1/blob/week-6/src/StatisticsUtils.java#L28) crashes with an empty list or with all values set to 0.
- [maxValue method](https://github.com/bvdheiden/TI1A2P1/blob/week-6/src/StatisticsUtils.java#L43) crashes with an empty list.
- [minValue method](https://github.com/bvdheiden/TI1A2P1/blob/week-6/src/StatisticsUtils.java#L64) crashes with an empty list.

Can this be addressed?
 @SemvdH @Anass738 @STavans @Wout02 @RemoMeijer

**Comment by SemvdH** [comment]
Will get on it
